"""__repr__ method added

Revision ID: 026eb7865da8
Revises: b87954241004
Create Date: 2023-05-11 17:17:52.225448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026eb7865da8'
down_revision = 'b87954241004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
