"""__repr__ method updated

Revision ID: 6955bb1709bb
Revises: 86a66df6f3c9
Create Date: 2023-05-11 23:25:12.976260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6955bb1709bb'
down_revision = '86a66df6f3c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
