"""__repr__ method updated

Revision ID: 86a66df6f3c9
Revises: 026eb7865da8
Create Date: 2023-05-11 23:24:14.301507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a66df6f3c9'
down_revision = '026eb7865da8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
