"""__repr__ method updated

Revision ID: b7cc2c163a78
Revises: 6955bb1709bb
Create Date: 2023-05-11 23:26:07.684706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cc2c163a78'
down_revision = '6955bb1709bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
