"""__repr__ method added

Revision ID: b87954241004
Revises: 86c9f1601ea2
Create Date: 2023-05-11 16:50:48.622251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87954241004'
down_revision = '86c9f1601ea2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
